// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ExchangeRates
{
    public partial class Rate
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public decimal? Rate1 { get; set; }
        public DateTime? TimeStamp { get; set; }
    }
}